sudo: required

services: 
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_cde0b98179cd_key -iv $encrypted_cde0b98179cd_iv -in multi-k8s-400412-6d1947813193.json.enc -out multi-k8s-400412-6d1947813193.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-400412-6d1947813193.json